<?php
return [
    'Senior Advocates' => [
        [
            'name' => 'Saif ur Rehman Gujjar',
            'role' => 'Advocate High Court',
            'qualification' => 'LLM, PU',
            'contact' => '0300-1234567',
            'email' => 'saif@example.com',
            'image' => asset('public/imgs/1hero.jpg'),
            'facebook' => 'https://facebook.com/saif',
            'twitter' => 'https://twitter.com/saif',
            'linkedin' => 'https://linkedin.com/in/saif',
        ],
        [
            'name' => 'Amir Ijaz Gujjar',
            'role' => 'Advocate High Court',
            'qualification' => 'LLB, KU',
            'contact' => '0301-6543210',
            'email' => 'amir@example.com',
            'image' => asset('public/imgs/1hero.jpg'),
            'facebook' => 'https://facebook.com/amir',
            'twitter' => 'https://twitter.com/amir',
            'linkedin' => 'https://linkedin.com/in/amir',
        ],
        [
            'name' => 'Khalil ur Rehman Gujjar',
            'role' => 'Advocate High Court',
            'qualification' => 'LLB, GCU',
            'contact' => '0320-1112233',
            'email' => 'khalil@example.com',
            'image' => asset('public/imgs/1hero.jpg'),
            'facebook' => 'https://facebook.com/khalil',
            'twitter' => 'https://twitter.com/khalil',
            'linkedin' => 'https://linkedin.com/in/khalil',
        ],
    ],

    'Advocates' => [
        [
            'name' => 'Ali Haider',
            'role' => 'Advocate High Court',
            'qualification' => 'LLB, UCP',
            'contact' => '0333-9876543',
            'email' => 'ali@example.com',
            'image' => asset('public/imgs/1hero.jpg'),
            'facebook' => 'https://facebook.com/ali',
            'twitter' => 'https://twitter.com/ali',
            'linkedin' => 'https://linkedin.com/in/ali',
        ],
        [
            'name' => 'Mian Kashif Sohail',
            'role' => 'Advocate High Court',
            'qualification' => 'LLB, PU',
            'contact' => '0345-2233445',
            'email' => 'kashif@example.com',
            'image' => asset('public/imgs/1hero.jpg'),
            'facebook' => 'https://facebook.com/kashif',
            'twitter' => 'https://twitter.com/kashif',
            'linkedin' => 'https://linkedin.com/in/kashif',
        ],
    ],

    'Junior Advocates' => [
        [
            'name' => 'Mian Wahaj',
            'role' => 'Advocate',
            'qualification' => 'LLB, UOL',
            'contact' => '0302-5566778',
            'email' => 'wahaj@example.com',
            'image' => asset('public/imgs/1hero.jpg'),
            'facebook' => 'https://facebook.com/wahaj',
            'twitter' => 'https://twitter.com/wahaj',
            'linkedin' => 'https://linkedin.com/in/wahaj',
        ],
        [
            'name' => 'Salman',
            'role' => 'Advocate',
            'qualification' => 'LLB, UMT',
            'contact' => '0343-6677889',
            'email' => 'salman@example.com',
            'image' => asset('public/imgs/1hero.jpg'),
            'facebook' => 'https://facebook.com/salman',
            'twitter' => 'https://twitter.com/salman',
            'linkedin' => 'https://linkedin.com/in/salman',
        ],
        [
            'name' => 'Hafiz M Adnan Ali Bhutta',
            'role' => 'Advocate',
            'qualification' => 'LLB, Islamia University',
            'contact' => '0332-1239876',
            'email' => 'adnan@example.com',
            'image' => asset('public/imgs/1hero.jpg'),
            'facebook' => 'https://facebook.com/adnan',
            'twitter' => 'https://twitter.com/adnan',
            'linkedin' => 'https://linkedin.com/in/adnan',
        ],
        [
            'name' => 'Hamza',
            'role' => 'Advocate',
            'qualification' => 'LLB, BZU',
            'contact' => '0311-8899001',
            'email' => 'hamza@example.com',
            'image' => asset('public/imgs/1hero.jpg'),
            'facebook' => 'https://facebook.com/hamza',
            'twitter' => 'https://twitter.com/hamza',
            'linkedin' => 'https://linkedin.com/in/hamza',
        ],
    ],

    'Internees' => [
        [
            'name' => 'Zulqarnain',
            'role' => 'Internee',
            'qualification' => 'LLB Student, UOL',
            'contact' => '0331-7654321',
            'email' => 'zulqarnain@example.com',
            'image' => asset('public/imgs/1hero.jpg'),
            'facebook' => 'https://facebook.com/zulqarnain',
            'twitter' => 'https://twitter.com/zulqarnain',
            'linkedin' => 'https://linkedin.com/in/zulqarnain',
        ],
        [
            'name' => 'Toheed',
            'role' => 'Internee',
            'qualification' => 'LLB Student, Punjab Law College',
            'contact' => '0315-1122334',
            'email' => 'toheed@example.com',
            'image' => asset('public/imgs/1hero.jpg'),
            'facebook' => 'https://facebook.com/toheed',
            'twitter' => 'https://twitter.com/toheed',
            'linkedin' => 'https://linkedin.com/in/toheed',
        ],
    ],

    'Clerks' => [
        [
            'name' => 'Hassan',
            'role' => 'Clerk',
            'qualification' => 'B.A',
            'contact' => '0308-9988776',
            'email' => 'hassan@example.com',
            'image' => asset('public/imgs/1hero.jpg'),
            'facebook' => 'https://facebook.com/hassan',
            'twitter' => 'https://twitter.com/hassan',
            'linkedin' => 'https://linkedin.com/in/hassan',
        ],
        [
            'name' => 'Sardar Awais Gujjar',
            'role' => 'Clerk',
            'qualification' => 'Intermediate',
            'contact' => '0309-2233445',
            'email' => 'awais@example.com',
            'image' => asset('public/imgs/1hero.jpg'),
            'facebook' => 'https://facebook.com/awais',
            'twitter' => 'https://twitter.com/awais',
            'linkedin' => 'https://linkedin.com/in/awais',
        ],
    ],
];
?>